"""
YouTube Analytics — Topic Modelling Pipeline
=============================================
Runs BERTopic on pre-computed embeddings from yt.nlp_embeddings to discover
granular topic clusters in your watch history. Populates yt.nlp_topics and
yt.nlp_video_topics.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RUN MODES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INCREMENTAL (default — use every quarter after new ETL ingest):
    REMAP = False
    - Loads the frozen topic map from models/bertopic/
    - Assigns only NEW videos (not yet in nlp_video_topics) to existing topics
    - Topic IDs never change — all temporal queries remain trustworthy
    - Runs in minutes

FULL REMAP (use when your interests have shifted significantly):
    REMAP = True
    - Recomputes all topics from scratch on all 54K+ videos
    - Truncates nlp_topics and nlp_video_topics and rewrites them
    - Saves a new frozen topic map to models/bertopic/
    - Runs in 15–30 minutes
    ⚠️  WARNING: After a remap, historical topic comparisons reset.
        Only trigger this when you consciously want a fresh topic map
        (recommended at most once per year).

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TOPIC HIERARCHY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    Level 1 (coarse) — dim_categories — YouTube's official taxonomy, already
                        populated from Tier 2 API enrichment. e.g. "Sports"

    Level 2 (granular) — nlp_topics — BERTopic clusters. e.g. "Boxing Highlights"
                          Each topic is anchored to a Level 1 category via
                          automatic majority-vote assignment.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LABEL GENERATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    Topic labels are generated by a local Llama 3.2 3B model via Ollama.
    Fully local, fully free, no API calls.

    Prerequisites:
        1. Install Ollama: https://ollama.com
        2. Pull the model: ollama pull llama3.2:3b
        3. Ensure Ollama is running: ollama serve

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PREREQUISITES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    pip install bertopic umap-learn hdbscan numba psycopg2-binary pgvector
                python-dotenv requests tqdm numpy

Usage:
    python topic_model.py
"""

import os
import re
import sys
import json
import time
import pickle
import logging
import warnings
import requests
import numpy as np
from pathlib import Path
from datetime import datetime, timezone
from collections import Counter

# Suppress noisy warnings from umap/numba on first run
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

try:
    import psycopg2
    from psycopg2.extras import execute_values
except ImportError:
    raise ImportError("Install psycopg2-binary: pip install psycopg2-binary")

try:
    from pgvector.psycopg2 import register_vector
except ImportError:
    raise ImportError("Install pgvector: pip install pgvector")

try:
    from bertopic import BERTopic
except ImportError:
    raise ImportError("Install bertopic: pip install bertopic")

try:
    from umap import UMAP
except ImportError:
    raise ImportError("Install umap-learn: pip install umap-learn")

try:
    from hdbscan import HDBSCAN
except ImportError:
    raise ImportError("Install hdbscan: pip install hdbscan")

try:
    import numba
except ImportError:
    raise ImportError("Install numba: pip install numba")

try:
    from dotenv import load_dotenv
except ImportError:
    raise ImportError("Install python-dotenv: pip install python-dotenv")

try:
    from tqdm import tqdm
except ImportError:
    raise ImportError("Install tqdm: pip install tqdm")

try:
    from langdetect import detect, LangDetectException
except ImportError:
    raise ImportError("Install langdetect: pip install langdetect")

try:
    from sklearn.feature_extraction.text import CountVectorizer
except ImportError:
    raise ImportError("Install scikit-learn: pip install scikit-learn")

# ============================================================================
# ┌─────────────────────────────────────────────────────────────────────────┐
# │                         RUN MODE SWITCH                                 │
# │                                                                         │
# │  REMAP = False  →  INCREMENTAL (default, use every quarter)             │
# │  REMAP = True   →  FULL REMAP  (use when interests shift significantly) │
# │                                                                         │
# │  See module docstring for full explanation of each mode.                │
# └─────────────────────────────────────────────────────────────────────────┘
REMAP = True
# ============================================================================


# ============================================================================
# Configuration
# ============================================================================

load_dotenv()

DB_CONFIG = {
    "dbname":   "youtube_analytics",
    "user":     "postgres",     # <-- Update if different
    "password": os.getenv("DB_PASSWORD", ""),
    "host":     "localhost",
    "port":     5432
}

# Model identity
MODEL_NAME      = "bertopic"
MODEL_VERSION   = "v1.0"

# BERTopic parameters
MIN_CLUSTER_SIZE    = 10    # Minimum videos to form a topic (tune: 10=very granular, 50=broad)
MIN_SAMPLES         = 5     # HDBSCAN: min samples for core point (tune: 5=more clusters, 15=fewer clusters)
N_NEIGHBORS         = 15    # UMAP: local vs global structure balance
N_COMPONENTS        = 10    # UMAP: output dimensions before clustering
RANDOM_STATE        = 42    # Fixed seed for reproducibility within a remap run

# Ollama configuration
OLLAMA_URL          = "http://localhost:11434/api/generate"
OLLAMA_MODEL        = "mistral:7b"
OLLAMA_TIMEOUT      = 30    # seconds per label request

# Paths — all relative to this script's location
BASE_DIR        = Path(__file__).parent
LOG_DIR         = BASE_DIR / "logs" / "ml_log"
REPORT_DIR      = BASE_DIR / "logs" / "topic_reports"
MODEL_DIR       = BASE_DIR / "models" / "bertopic"


# ============================================================================
# Database Support Tables (auto-created if missing)
# ============================================================================

CREATE_TOPIC_LOG = """
CREATE TABLE IF NOT EXISTS yt.topic_log (
    log_id              SERIAL          PRIMARY KEY,
    run_at              TIMESTAMPTZ     DEFAULT NOW(),
    run_mode            VARCHAR(20)     NOT NULL,   -- 'incremental' or 'remap'
    model_name          VARCHAR(100)    NOT NULL,
    model_version       VARCHAR(50),
    videos_processed    INTEGER         NOT NULL DEFAULT 0,
    videos_assigned     INTEGER         NOT NULL DEFAULT 0,
    videos_outlier      INTEGER         NOT NULL DEFAULT 0,
    topics_created      INTEGER         NOT NULL DEFAULT 0,
    topics_total        INTEGER         NOT NULL DEFAULT 0,
    duration_seconds    FLOAT
);

COMMENT ON TABLE yt.topic_log IS
    'Audit log for topic modelling runs. Tracks topic counts, assignments, '
    'outliers, and whether the run was incremental or a full remap.';
"""


# ============================================================================
# Logging Setup
# ============================================================================

def setup_logger(log_dir: Path) -> logging.Logger:
    """Configure per-run timestamped logger writing to ml_log/ and console."""
    log_dir.mkdir(parents=True, exist_ok=True)
    run_ts   = datetime.now().strftime("%Y-%m-%d_%H-%M")
    log_path = log_dir / f"topic_{run_ts}.log"

    logger = logging.getLogger("topic_model")
    logger.setLevel(logging.DEBUG)

    fh = logging.FileHandler(log_path, encoding="utf-8")
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(logging.Formatter(
        "%(asctime)s | %(levelname)-8s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S"
    ))

    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)
    ch.setFormatter(logging.Formatter("%(message)s"))

    logger.addHandler(fh)
    logger.addHandler(ch)
    logger.info(f"Log file: {log_path}")
    return logger


# ============================================================================
# numba Thread Configuration
# ============================================================================

def configure_numba(logger: logging.Logger):
    """
    Cap numba threads to leave 2 performance cores free for the OS.
    Prevents the machine from becoming unresponsive during UMAP computation.
    Thermal safety: M-series chips throttle gracefully but we reduce load anyway.
    """
    total_threads   = numba.get_num_threads()
    safe_threads    = max(1, total_threads - 2)
    numba.set_num_threads(safe_threads)
    logger.info(f"numba threads: {safe_threads} of {total_threads} (2 reserved for OS)")

# ============================================================================
# Detecting Keyword Language
# ============================================================================
def detect_keyword_language(keywords: list[str]) -> str:
    """
    Detect the dominant language of a topic's keywords.
    Returns an ISO 639-1 language code e.g. 'en', 'da', 'es', 'de'.
    Falls back to 'en' if detection fails.
    """
    try:
        sample = " ".join(keywords[:8])
        return detect(sample)
    except LangDetectException:
        return "en"


# ============================================================================
# Ollama Label Generation
# ============================================================================
# Ollama refusal detection — if the model refuses, fall back to keywords
REFUSAL_PATTERNS = [
    "i cannot", "i'm unable", "i am unable",
    "i apologize", "i'm sorry", "i am sorry",
    "not appropriate", "harmful content",
    "i can't", "i will not", "i won't"
]

def generate_label_ollama(keywords: list[str],
                           category_name: str,
                           logger: logging.Logger) -> str:
    """
    Generate a human-readable topic label using Ollama (Llama 3.2 3B).
    Falls back to a keyword-based label if Ollama is unavailable.

    Args:
        keywords:      Top keywords for this topic from BERTopic
        category_name: YouTube category (Level 1 context for the model)
        logger:        Logger instance

    Returns:
        A concise human-readable label string (3–5 words)
    """
    # 1. Build keyword string first
    keyword_str = ", ".join(keywords[:10])

    # 2. Detect language using keywords
    lang = detect_keyword_language(keywords)
    lang_note = ""
    if lang != "en":
        lang_map = {
            "da": "Danish", "es": "Spanish", "de": "German",
            "ka": "Georgian", "fr": "French", "nl": "Dutch",
            "no": "Norwegian", "sv": "Swedish"
        }
        lang_name = lang_map.get(lang, f"non-English ({lang})")
        lang_note = f"Note: keywords appear to be in {lang_name}.\n"
    
    # 3. Build prompt using both
    prompt = (
        f"You are labelling a YouTube topic cluster.\n"
        f"YouTube category: {category_name}\n"
        f"{lang_note}"
        f"Top keywords from this cluster: {keyword_str}\n\n"
        f"Rules:\n"
        f"- If keywords contain a band, artist, creator, or athlete name, "
        f"use it in the label (e.g. 'The War on Drugs' not 'War Music')\n"
        f"- If keywords are mostly non-English, label as "
        f"'[Language] Content' e.g. 'Danish Media Content'\n"
        f"- Be specific, not generic — avoid vague labels like "
        f"'Video Content' or 'Online Media'\n"
        f"- 3-5 words maximum\n"
        f"- Reply with ONLY the label, nothing else. "
        f"Do not explain, do not refuse, just write the label."
    )

    try:
        response = requests.post(
            OLLAMA_URL,
            json={
                "model":  OLLAMA_MODEL,
                "prompt": prompt,
                "stream": False,
                "options": {"temperature": 0.2}   # Low temp = consistent labels
            },
            timeout=OLLAMA_TIMEOUT
        )
        response.raise_for_status()
        label = response.json().get("response", "").strip()

        # Sanitise: remove quotes, limit length
        label = re.sub(r'^["\']|["\']$', '', label).strip()
        label = label[:100] if label else ""

        # Detect refusals — fall back to keyword label
        if label and any(label.lower().startswith(p) for p in REFUSAL_PATTERNS):
            logger.warning(f"Ollama refused to label: {keywords[:5]}")
            label = ""

        if label:
            return label

    except requests.ConnectionError:
        logger.warning("Ollama not reachable — falling back to keyword label")
    except requests.Timeout:
        logger.warning(f"Ollama timeout for keywords: {keyword_str[:50]}")
    except Exception as e:
        logger.warning(f"Ollama error: {e}")

    # Fallback: capitalise and join top 4 keywords
    return " / ".join(k.title() for k in keywords[:4])


# ============================================================================
# Automatic Category Assignment
# ============================================================================

def assign_category(video_ids: list[str],
                    video_category_map: dict[str, int]) -> int | None:
    """
    Majority-vote: assign the most common YouTube category_id among
    the videos in this topic cluster.

    Args:
        video_ids:          Video IDs in this topic cluster
        video_category_map: Mapping of video_id -> category_id

    Returns:
        The majority category_id, or None if no category data available
    """
    category_ids = [
        video_category_map[vid]
        for vid in video_ids
        if vid in video_category_map and video_category_map[vid] is not None
    ]
    if not category_ids:
        return None
    return Counter(category_ids).most_common(1)[0][0]


# ============================================================================
# Model Persistence
# ============================================================================

def save_model(topic_model: BERTopic,
               metadata: dict,
               model_dir: Path,
               logger: logging.Logger):
    """Save the fitted BERTopic model and run metadata to models/bertopic/."""
    model_dir.mkdir(parents=True, exist_ok=True)

    # Save BERTopic model (handles its own serialisation)
    model_path = model_dir / "bertopic_model"
    topic_model.save(str(model_path), serialization="pickle")
    logger.info(f"BERTopic model saved → {model_path}")

    # Save metadata
    meta_path = model_dir / "metadata.json"
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2, default=str)
    logger.info(f"Metadata saved       → {meta_path}")


def load_model(model_dir: Path,
               logger: logging.Logger) -> BERTopic | None:
    """Load a previously saved BERTopic model. Returns None if not found."""
    model_path = model_dir / "bertopic_model"
    if not model_path.exists():
        return None
    logger.info(f"Loading saved model from {model_path}...")
    topic_model = BERTopic.load(str(model_path))
    logger.info("Saved model loaded.")
    return topic_model


# ============================================================================
# Topic Report
# ============================================================================

def write_topic_report(topics: list[dict],
                       report_dir: Path,
                       run_mode: str,
                       logger: logging.Logger):
    """
    Write a human-readable topic discovery report to logs/topic_reports/.
    One file per run, timestamped. Primary tool for exploring discovered topics
    without writing SQL.
    """
    report_dir.mkdir(parents=True, exist_ok=True)
    run_ts      = datetime.now().strftime("%Y-%m-%d_%H-%M")
    report_path = report_dir / f"topic_report_{run_ts}.txt"

    lines = [
        "=" * 70,
        f"  TOPIC DISCOVERY REPORT",
        f"  Run mode:  {run_mode.upper()}",
        f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"  Topics:    {len(topics)}",
        "=" * 70,
        "",
    ]

    # Sort by video count descending
    for t in sorted(topics, key=lambda x: x["video_count"], reverse=True):
        lines += [
            f"Topic {t['topic_id']:>4}  |  {t['topic_label']}",
            f"  Category:  {t['category_name'] or 'Unassigned'}",
            f"  Videos:    {t['video_count']:,}",
            f"  Keywords:  {', '.join(t['keywords'][:10])}",
            "",
        ]

    report_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info(f"Topic report saved   → {report_path}")


# ============================================================================
# Core Pipeline — Full Remap
# ============================================================================

def run_remap(conn, cur, logger: logging.Logger) -> dict:
    """
    Full remap: recompute all topics from scratch.
    Truncates nlp_topics and nlp_video_topics, rebuilds from all active
    embedded videos, saves new frozen model to models/bertopic/.

    Returns run statistics dict.
    """
    start_time = time.time()
    logger.info("")
    logger.info("=" * 60)
    logger.info("  MODE: FULL REMAP")
    logger.info("  All topics will be recomputed from scratch.")
    logger.info("  nlp_topics and nlp_video_topics will be truncated.")
    logger.info("=" * 60)
    logger.info("")

    # ----------------------------------------------------------------
    # STEP 1: Load all active embedded videos
    # ----------------------------------------------------------------
    logger.info("Loading embeddings for all active videos...")
    cur.execute("""
        SELECT
            ne.video_id,
            ne.embedding,
            dv.category_id,
            dc.category_name,
            COALESCE(dv.title, '') AS title
        FROM   yt.nlp_embeddings ne
        JOIN   yt.dim_videos dv      ON ne.video_id = dv.video_id
        LEFT JOIN yt.dim_categories dc ON dv.category_id = dc.category_id
        WHERE  dv.status = 'active'
        AND    ne.embed_failed_at IS NULL
        ORDER  BY ne.video_id
    """)
    rows = cur.fetchall()

    video_ids           = [r[0] for r in rows]
    embeddings          = np.array([r[1] for r in rows], dtype=np.float32)
    video_category_map  = {r[0]: r[2] for r in rows}
    category_name_map   = {r[2]: r[3] for r in rows if r[2] is not None}
    documents           = [r[4] if r[4].strip() else "unknown" for r in rows]

    logger.info(f"Loaded {len(video_ids):,} embeddings  "
                f"(shape: {embeddings.shape})")

    # ----------------------------------------------------------------
    # STEP 2: Build and fit BERTopic model
    # ----------------------------------------------------------------
    logger.info("")
    logger.info("Configuring UMAP (numba-accelerated)...")
    umap_model = UMAP(
        n_neighbors=N_NEIGHBORS,
        n_components=N_COMPONENTS,
        metric="cosine",
        random_state=RANDOM_STATE,
        low_memory=False,       # Faster on machines with enough RAM
        verbose=False
    )

    logger.info("Configuring HDBSCAN...")
    hdbscan_model = HDBSCAN(
        min_cluster_size=MIN_CLUSTER_SIZE,
        min_samples=MIN_SAMPLES,
        metric="euclidean",     # Post-UMAP space uses euclidean
        cluster_selection_method="eom",
        prediction_data=True    # Required for incremental assignment later
    )

    logger.info("Building BERTopic model...")
    vectorizer = CountVectorizer(
        stop_words="english",   # Filters out she/her/this/when etc.
        min_df=2,               # Word must appear in at least 2 documents
        ngram_range=(1, 2)      # Allows two-word phrases e.g. "war drugs"
    )
    topic_model = BERTopic(
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        vectorizer_model=vectorizer,
        verbose=False,
        calculate_probabilities=False
    )

    logger.info("Fitting BERTopic on embeddings (this is the slow step)...")
    logger.info(f"  Min cluster size: {MIN_CLUSTER_SIZE}")
    logger.info(f"  UMAP n_neighbors: {N_NEIGHBORS}")
    logger.info(f"  UMAP n_components: {N_COMPONENTS}")
    logger.info(f"  Random state: {RANDOM_STATE}")
    logger.info("")

    fit_start = time.time()
    topics_raw, _ = topic_model.fit_transform(
        documents=documents,    # Titles used for keyword extraction (c-TF-IDF)
        embeddings=embeddings   # Embeddings drive the actual clustering
    )
    fit_duration = time.time() - fit_start
    logger.info(f"BERTopic fit complete in {fit_duration:.1f}s")

    # ----------------------------------------------------------------
    # STEP 3: Extract topic info
    # ----------------------------------------------------------------
    topic_info  = topic_model.get_topic_info()
    # Topic -1 is the outlier bucket — exclude from DB writes
    valid_topics = topic_info[topic_info["Topic"] != -1]
    n_topics    = len(valid_topics)
    n_outliers  = int((np.array(topics_raw) == -1).sum())

    logger.info(f"Topics discovered:   {n_topics:,}")
    logger.info(f"Outlier videos (-1): {n_outliers:,}  (left unassigned)")

    # ----------------------------------------------------------------
    # STEP 4: Generate labels via Ollama
    # ----------------------------------------------------------------
    logger.info("")
    logger.info("Generating topic labels via Ollama (Llama 3.2 3B)...")
    logger.info("  (Ensure Ollama is running: ollama serve)")
    logger.info("")

    topic_rows      = []    # For nlp_topics inserts
    report_topics   = []    # For the human-readable report

    # Build video→topic mapping for category assignment
    vid_to_topic = {
        vid: topic_id
        for vid, topic_id in zip(video_ids, topics_raw)
        if topic_id != -1
    }

    # Group video_ids by topic
    topic_video_groups: dict[int, list[str]] = {}
    for vid, tid in vid_to_topic.items():
        topic_video_groups.setdefault(tid, []).append(vid)

    with tqdm(total=n_topics, unit="topic",
              desc="Labelling", dynamic_ncols=True) as pbar:

        for _, row in valid_topics.iterrows():
            bertopic_id     = int(row["Topic"])
            topic_terms     = topic_model.get_topic(bertopic_id)
            if isinstance(topic_terms, list):
                keywords = [w for w, _ in topic_terms]
            else:
                logger.warning(f"Unexpected topic terms for topic {bertopic_id}: {type(topic_terms).__name__}")
                keywords = []
            if not keywords:
                keywords = ["unknown"]

            # Majority-vote category assignment
            cluster_vids    = topic_video_groups.get(bertopic_id, [])
            category_id     = assign_category(cluster_vids, video_category_map)
            category_name   = category_name_map.get(category_id, "Unknown")

            # LLM label
            label = generate_label_ollama(keywords, category_name, logger)

            topic_rows.append({
                "bertopic_id":  bertopic_id,
                "topic_label":  label,
                "keywords":     keywords[:15],
                "category_id":  category_id,
                "video_count":  len(cluster_vids),
            })

            report_topics.append({
                "topic_id":     bertopic_id,
                "topic_label":  label,
                "keywords":     keywords,
                "category_name": category_name,
                "video_count":  len(cluster_vids),
            })

            pbar.update(1)

    # ----------------------------------------------------------------
    # STEP 5: Write to database
    # ----------------------------------------------------------------
    logger.info("")
    logger.info("Writing topics to database...")

    # Truncate existing topic data (full remap replaces everything)
    cur.execute("TRUNCATE yt.nlp_video_topics CASCADE;")
    cur.execute("TRUNCATE yt.nlp_topics CASCADE;")
    conn.commit()

    # Build a bertopic_id → db topic_id map after insert
    bertopic_to_db: dict[int, int] = {}

    for t in topic_rows:
        cur.execute(
            """
            INSERT INTO yt.nlp_topics
                (topic_label, keywords, model_name, model_version, category_id)
            VALUES (%s, %s, %s, %s, %s)
            RETURNING topic_id
            """,
            (
                t["topic_label"],
                t["keywords"],
                MODEL_NAME,
                MODEL_VERSION,
                t["category_id"],
            )
        )
        db_topic_id = cur.fetchone()[0]
        bertopic_to_db[t["bertopic_id"]] = db_topic_id

    conn.commit()
    logger.info(f"  Inserted {len(topic_rows):,} topics into nlp_topics")

    # Insert video→topic assignments
    logger.info("Writing video topic assignments...")
    assignment_rows = []
    videos_assigned = 0

    for vid, bertopic_id in vid_to_topic.items():
        if bertopic_id in bertopic_to_db:
            assignment_rows.append((vid, bertopic_to_db[bertopic_id], 1.0))

    if assignment_rows:
        execute_values(
            cur,
            """
            INSERT INTO yt.nlp_video_topics (video_id, topic_id, score)
            VALUES %s
            ON CONFLICT (video_id, topic_id) DO NOTHING
            """,
            assignment_rows,
            page_size=1000
        )
        conn.commit()
        videos_assigned = len(assignment_rows)

    logger.info(f"  Assigned {videos_assigned:,} videos to topics")

    # ----------------------------------------------------------------
    # STEP 6: Save model to disk
    # ----------------------------------------------------------------
    metadata = {
        "run_mode":         "remap",
        "run_at":           datetime.now(timezone.utc).isoformat(),
        "model_name":       MODEL_NAME,
        "model_version":    MODEL_VERSION,
        "min_cluster_size": MIN_CLUSTER_SIZE,
        "n_neighbors":      N_NEIGHBORS,
        "n_components":     N_COMPONENTS,
        "random_state":     RANDOM_STATE,
        "n_topics":         n_topics,
        "n_videos":         len(video_ids),
        "n_outliers":       n_outliers,
        "fit_duration_s":   round(fit_duration, 2),
        "bertopic_to_db":   {str(k): v for k, v in bertopic_to_db.items()},
    }
    save_model(topic_model, metadata, MODEL_DIR, logger)

    # ----------------------------------------------------------------
    # STEP 7: Write topic report
    # ----------------------------------------------------------------
    # Add DB topic_ids to report topics
    for t in report_topics:
        t["topic_id"] = bertopic_to_db.get(t["topic_id"], t["topic_id"])

    write_topic_report(report_topics, REPORT_DIR, "remap", logger)

    return {
        "run_mode":         "remap",
        "videos_processed": len(video_ids),
        "videos_assigned":  videos_assigned,
        "videos_outlier":   n_outliers,
        "topics_created":   n_topics,
        "topics_total":     n_topics,
        "duration":         time.time() - start_time,
    }


# ============================================================================
# Core Pipeline — Incremental
# ============================================================================

def run_incremental(conn, cur, logger: logging.Logger) -> dict:
    """
    Incremental run: assign only NEW videos (not yet in nlp_video_topics)
    to the nearest existing topic using cosine similarity.

    Topic IDs are never changed — all historical queries remain valid.

    Returns run statistics dict.
    """
    start_time = time.time()
    logger.info("")
    logger.info("=" * 60)
    logger.info("  MODE: INCREMENTAL")
    logger.info("  Only new videos will be assigned to existing topics.")
    logger.info("  Topic IDs are frozen and unchanged.")
    logger.info("=" * 60)
    logger.info("")

    # ----------------------------------------------------------------
    # STEP 1: Load the frozen topic map
    # ----------------------------------------------------------------
    topic_model = load_model(MODEL_DIR, logger)
    if topic_model is None:
        logger.error(
            "No saved model found in models/bertopic/.\n"
            "  Run with REMAP = True first to build the initial topic map."
        )
        sys.exit(1)

    # Load metadata for bertopic_id → db topic_id mapping
    meta_path = MODEL_DIR / "metadata.json"
    if not meta_path.exists():
        logger.error("metadata.json not found in models/bertopic/. Cannot map topic IDs.")
        sys.exit(1)

    with open(meta_path, encoding="utf-8") as f:
        metadata = json.load(f)

    bertopic_to_db: dict[int, int] = {
        int(k): v for k, v in metadata.get("bertopic_to_db", {}).items()
    }

    # ----------------------------------------------------------------
    # STEP 2: Find new videos not yet assigned
    # ----------------------------------------------------------------
    logger.info("Finding new unassigned active videos...")
    cur.execute("""
        SELECT
            ne.video_id,
            ne.embedding
        FROM   yt.nlp_embeddings ne
        JOIN   yt.dim_videos dv ON ne.video_id = dv.video_id
        WHERE  dv.status = 'active'
        AND    ne.embed_failed_at IS NULL
        AND    ne.video_id NOT IN (
                   SELECT DISTINCT video_id FROM yt.nlp_video_topics
               )
        ORDER  BY ne.video_id
    """)
    rows = cur.fetchall()

    if not rows:
        logger.info("No new videos to assign. Database is up to date.")
        return {
            "run_mode":         "incremental",
            "videos_processed": 0,
            "videos_assigned":  0,
            "videos_outlier":   0,
            "topics_created":   0,
            "topics_total":     metadata.get("n_topics", 0),
            "duration":         time.time() - start_time,
        }

    video_ids   = [r[0] for r in rows]
    embeddings  = np.array([r[1] for r in rows], dtype=np.float32)
    logger.info(f"Found {len(video_ids):,} new videos to assign")

    # ----------------------------------------------------------------
    # STEP 3: Transform new embeddings through the frozen UMAP + assign topics
    # ----------------------------------------------------------------
    logger.info("Transforming embeddings through frozen UMAP...")
    topics_raw, _ = topic_model.transform(
        documents=["" for _ in video_ids],
        embeddings=embeddings
    )

    # ----------------------------------------------------------------
    # STEP 4: Write assignments
    # ----------------------------------------------------------------
    assignment_rows = []
    n_outliers      = 0

    for vid, bertopic_id in zip(video_ids, topics_raw):
        if bertopic_id == -1:
            n_outliers += 1
            continue    # Outliers left unassigned per design decision
        db_topic_id = bertopic_to_db.get(int(bertopic_id))
        if db_topic_id is not None:
            assignment_rows.append((vid, db_topic_id, 1.0))

    videos_assigned = 0
    if assignment_rows:
        logger.info(f"Writing {len(assignment_rows):,} assignments to database...")
        execute_values(
            cur,
            """
            INSERT INTO yt.nlp_video_topics (video_id, topic_id, score)
            VALUES %s
            ON CONFLICT (video_id, topic_id) DO NOTHING
            """,
            assignment_rows,
            page_size=1000
        )
        conn.commit()
        videos_assigned = len(assignment_rows)

    logger.info(f"  Assigned: {videos_assigned:,}")
    logger.info(f"  Outliers: {n_outliers:,}  (left unassigned)")

    # Get current total topic count from DB
    cur.execute("SELECT COUNT(*) FROM yt.nlp_topics")
    topics_total = cur.fetchone()[0]

    return {
        "run_mode":         "incremental",
        "videos_processed": len(video_ids),
        "videos_assigned":  videos_assigned,
        "videos_outlier":   n_outliers,
        "topics_created":   0,
        "topics_total":     topics_total,
        "duration":         time.time() - start_time,
    }


# ============================================================================
# Main Entry Point
# ============================================================================

def run_topic_model():
    """
    Orchestrate the topic modelling pipeline.
    Dispatches to run_remap() or run_incremental() based on the REMAP flag.
    """
    logger = setup_logger(LOG_DIR)

    logger.info(f"Run mode: {'FULL REMAP' if REMAP else 'INCREMENTAL'}")
    logger.info(f"Model:    {MODEL_NAME} / {OLLAMA_MODEL} (labels)")
    logger.info("")

    configure_numba(logger)

    # ----------------------------------------------------------------
    # Database connection
    # ----------------------------------------------------------------
    logger.info("Connecting to database...")
    conn = psycopg2.connect(**DB_CONFIG)
    conn.autocommit = False
    register_vector(conn)
    cur = conn.cursor()

    try:
        cur.execute("SET search_path TO yt, public;")

        # Ensure topic_log exists
        cur.execute(CREATE_TOPIC_LOG)
        conn.commit()

        # ----------------------------------------------------------------
        # Dispatch to correct run mode
        # ----------------------------------------------------------------
        if REMAP:
            stats = run_remap(conn, cur, logger)
        else:
            stats = run_incremental(conn, cur, logger)

        # ----------------------------------------------------------------
        # Log the run
        # ----------------------------------------------------------------
        cur.execute(
            """
            INSERT INTO yt.topic_log (
                run_mode, model_name, model_version,
                videos_processed, videos_assigned, videos_outlier,
                topics_created, topics_total, duration_seconds
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                stats["run_mode"], MODEL_NAME, MODEL_VERSION,
                stats["videos_processed"], stats["videos_assigned"],
                stats["videos_outlier"], stats["topics_created"],
                stats["topics_total"], round(stats["duration"], 2)
            )
        )
        conn.commit()

        # ----------------------------------------------------------------
        # Summary report
        # ----------------------------------------------------------------
        logger.info("")
        logger.info("=" * 60)
        logger.info(f"  TOPIC MODELLING COMPLETE  [{stats['run_mode'].upper()}]")
        logger.info("=" * 60)
        logger.info(f"  Duration:            {stats['duration']:.1f}s  "
                    f"({stats['duration']/60:.1f} min)")
        logger.info(f"  ─────────────────────────────────────")
        logger.info(f"  Videos processed:    {stats['videos_processed']:>8,}")
        logger.info(f"  Videos assigned:     {stats['videos_assigned']:>8,}")
        logger.info(f"  Videos outlier:      {stats['videos_outlier']:>8,}")
        logger.info(f"  Topics created:      {stats['topics_created']:>8,}")
        logger.info(f"  Topics total in DB:  {stats['topics_total']:>8,}")
        if stats["run_mode"] == "remap":
            logger.info(f"  ─────────────────────────────────────")
            logger.info(f"  Model saved → models/bertopic/")
            logger.info(f"  Report saved → logs/topic_reports/")
        logger.info("=" * 60)

    except Exception as e:
        conn.rollback()
        logger.error(f"\nFATAL ERROR: {e}")
        raise
    finally:
        cur.close()
        conn.close()
        logger.info("Database connection closed.")


# ============================================================================
# Main
# ============================================================================

if __name__ == "__main__":
    run_topic_model()
